In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
mails_data=pd.read_csv('E:\Personal\DataScience\MachineLearning\SpamMails.csv',encoding = 'unicode_escape')

In [5]:
mails_data.head()

  Category                                            Message Unnamed: 2
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN

In [6]:
mails_data.drop(columns=['Unnamed: 2'],axis=1,inplace=True)

In [7]:
mails_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

The below code is not a good example as it deletes the original data. Hence we should apply the lambda function and add it in a new column and then drop the required column.

In [8]:
mails_data['Category']=mails_data['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [9]:
mails_data.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

The below command is to rename the columns in a DF if required.

In [11]:
mails_data.rename(columns={'Category': 'Spam Mail'},inplace=True)

Now we will run the process again from the begining.

In [12]:
df_mails=pd.read_csv('E:\Personal\DataScience\MachineLearning\SpamMails.csv',encoding = 'unicode_escape')

In [13]:
df_mails.head()

  Category                                            Message Unnamed: 2
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN

In [15]:
df_mails.drop(columns=['Unnamed: 2'],axis=1,inplace=True)

KeyError: "['Unnamed: 2'] not found in axis"

The above error is coming due to the fact that the column was already dropped

In [16]:
df_mails['SpamMail']=df_mails['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [17]:
df_mails.head()

  Category                                            Message  SpamMail
0      ham  Go until jurong point, crazy.. Available only ...         0
1      ham                      Ok lar... Joking wif u oni...         0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...         1
3      ham  U dun say so early hor... U c already then say...         0
4      ham  Nah I don't think he goes to usf, he lives aro...         0

In [18]:
df_mails.drop('Category',axis=1,inplace=True)

In [19]:
df_mails.head()

                                             Message  SpamMail
0  Go until jurong point, crazy.. Available only ...         0
1                      Ok lar... Joking wif u oni...         0
2  Free entry in 2 a wkly comp to win FA Cup fina...         1
3  U dun say so early hor... U c already then say...         0
4  Nah I don't think he goes to usf, he lives aro...         0

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vector=CountVectorizer()

In [21]:
X_vector=vector.fit_transform(df_mails['Message'])

In [37]:
X_vector.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
X_vector.toarray().shape

(5574, 8700)

In [26]:
vector.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08704050406',
 '08704439680',
 '08704439680ts',
 '08706091795',
 '0870737910216yrs',
 '08707500020',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708034412',
 '08708800282',
 '08709222922',
 '08709501522',
 '0871',
 '087104711148',
 '08712101358',
 '08712103738',
 '0871212025016',
 '08712300220',
 '087123002209am',
 '08712317606',
 '08712400200',
 '08712400602450p',
 '08712400603',
 '08712402050',
 '08712402578',
 '08712402779',
 '08712402902',
 '08712402972',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712466669',
 '0871277810710p',
 '0871277810810',
 '0871277810910p',
 '08714342399',
 '087147123779am',
 '08714712379',
 '08714712388',
 '08714712394',
 '08714712412',
 '08714714011',
 '08715203028',
 '08715203649',
 '08715203652',
 '08715203656',
 '08715203677',
 '08715203685',
 '08715203694',
 '08715205273',
 '08715500022',
 '08715705022',
 '08717111821',
 '08717168528',
 '08717205546',
 '0871750',
 '08717507382',
 '08717509990',
 '08717890890',
 '08717895698',
 '08717898035',
 '08718711108',
 '08718720201',
 '08718723815',
 '08718725756',
 '08718726270',
 '087187262701',
 '08718726970',
 '08718726971',
 '08718726978',
 '087187272008',
 '08718727870',
 '08718727870150ppm',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738002',
 '08718738034',
 '08719180219',
 '08719180248',
 '08719181259',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719899217',
 '08719899229',
 '08719899230',
 '09',
 '09041940223',
 '09050000301',
 '09050000332',
 '09050000460',
 '09050000555',
 '09050000878',
 '09050000928',
 '09050001295',
 '09050001808',
 '09050003091',
 '09050005321',
 '09050090044',
 '09050280520',
 '09053750005',
 '09056242159',
 '09057039994',
 '09058091854',
 '09058091870',
 '09058094454',
 '09058094455',
 '09058094507',
 '09058094565',
 '09058094583',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058095201',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104276',
 '09061104283',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701444',
 '09061701461',
 '09061701851',
 '09061701939',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061743810',
 '09061743811',
 '09061744553',
 '09061749602',
 '09061790121',
 '09061790125',
 '09061790126',
 '09063440451',
 '09063442151',
 '09063458130',
 '0906346330',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064015307',
 '09064017295',
 '09064017305',
 '09064018838',
 '09064019014',
 '09064019788',
 '09065069120',
 '09065069154',
 '09065171142',
 '09065174042',
 '09065394514',
 '09065394973',
 '09065989180',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364349',
 '09066364589',
 '09066368327',
 '09066368470',
 '09066368753',
 '09066380611',
 '09066382422',
 '09066612661',
 '09066649731from',
 '09066660100',
 '09071512432',
 '09071512433',
 '09071517866',
 '09077818151',
 '09090204448',
 '09090900040',
 '09094100151',
 '09094646631',
 '09094646899',
 '09095350301',
 '09096102316',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726481',
 '09099726553',
 '09111030116',
 '09111032124',
 '09701213186',
 '0a',
 '0quit',
 '10',
 '100',
 '1000',
 '1000call',
 '1000s',
 '100p',
 '100percent',
 '100txt',
 '1013',
 '1030',
 '10am',
 '10k',
 '10p',
 '10ppm',
 '10th',
 '11',
 '1120',
 '113',
 '1131',
 '114',
 '1146',
 '116',
 '1172',
 '118p',
 '11mths',
 '11pm',
 '12',
 '1205',
 '120p',
 '121',
 '1225',
 '123',
 '125',
 '1250',
 '125gift',
 '128',
 '12hours',
 '12hrs',
 '12mths',
 '13',
 '130',
 '1327',
 '139',
 '14',
 '140',
 '1405',
 '140ppm',
 '145',
 '1450',
 '146tf150p',
 '14tcr',
 '14thmarch',
 '15',
 '150',
 '1500',
 '150p',
 '150p16',
 '150pm',
 '150ppermesssubscription',
 '150ppm',
 '150ppmpobox10183bhamb64xe',
 '150ppmsg',
 '150pw',
 '151',
 '153',
 '15541',
 '15pm',
 '16',
 '165',
 '1680',
 '169',
 '177',
 '18',
 '180',
 '1843',
 '18p',
 '18yrs',
 '195',
 '1956669',
 '1apple',
 '1b6a5ecef91ff9',
 '1cup',
 '1da',
 '1er',
 '1hr',
 '1im',
 '1lemon',
 '1mega',
 '1million',
 '1pm',
 '1st',
 '1st4terms',
 '1stchoice',
 '1stone',
 '1thing',
 '1tulsi',
 '1win150ppmx3',
 '1winaweek',
 '1winawk',
 '1x150p',
 '1yf',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '200p',
 '2025050',
 '20m12aq',
 '20p',
 '21',
 '21870000',
 '21st',
 '22',
 '220',
 '220cm2',
 '2309',
 '23f',
 '23g',
 '24',
 '24hrs',
 '24m',
 '24th',
 '25',
 '250',
 '250k',
 '255',
 '25p',
 '26',
 '2667',
 '26th',
 '27',
 '28',
 '2814032',
 '28days',
 '28th',
 '28thfeb',
 '29',
 '2b',
 '2bold',
 '2c',
 '2channel',
 '2day',
 '2docd',
 '2end',
 '2exit',
 '2ez',
 '2find',
 '2getha',
 '2geva',
 '2go',
 '2gthr',
 '2hook',
 '2hrs',
 '2i',
 '2kbsubject',
 '2lands',
 '2marrow',
 '2moro',
 '2morow',
 '2morro',
 '2morrow',
 '2morrowxxxx',
 '2mro',
 '2mrw',
 '2mwen',
 '2nd',
 '2nhite',
 '2nights',
 '2nite',
 '2optout',
 '2p',
 '2price',
 '2px',
 '2rcv',
 '2stop',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2u2',
 '2watershd',
 '2waxsto',
 '2wks',
 '2wt',
 '2wu',
 '2years',
 '2yr',
 '2yrs',
 '30',
 '300',
 '3000',
 '300603',
 '300603t',
 '300p',
 '3030',
 '30apr',
 '30ish',
 '30pm',
 '30pp',
 '30s',
 '30th',
 '31',
 '3100',
 '310303',
 '31p',
 '32',
 '32000',
 '3230',
 '32323',
 '326',
 '33',
 '330',
 '350',
 '3510i',
 '35p',
 '3650',
 '36504',
 '3680',
 '373',
 '3750',
 '37819',
 '38',
 '382',
 '391784',
 '3aj',
 '3d',
 '3days',
 '3g',
 '3gbp',
 '3hrs',
 '3lions',
 '3lp',
 '3miles',
 '3mins',
 '3mobile',
 '3optical',
 '3pound',
 '3qxj9',
 '3rd',
 '3ss',
 '3uz',
 '3wks',
 '3x',
 '3xx',
 '40',
 '400',
 '400mins',
 '400thousad',
 '402',
 '4041',
 '40411',
 '40533',
 '40gb',
 '40mph',
 '41685',
 '41782',
 '420',
 '42049',
 '4217',
 '42478',
 '42810',
 '430',
 '434',
 '44',
 '440',
 '4403ldnw1a7rw18',
 '44345',
 '447797706009',
 '447801259231',
 '448712404000',
 '449050000301',
 '45',
 '450',
 '450p',
 '450ppw',
 '450pw',
 '45239',
 '45pm',
 '47',
 '4719',
 '4742',
 '47per',
 '48',
 '4882',
 '48922',
 '49',
 '49557',
 '4a',
 '4brekkie',
 '4d',
 '4eva',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4got',
 '4goten',
 '4info',
 '4jx',
 '4msgs',
 '4mths',
 '4my',
 '4qf2',
 '4t',
 '4th',
 '4the',
 '4txt',
 '4u',
 '4utxt',
 '4w',
 '4ward',
 '4wrd',
 '4xx26',
 '4years',
 '50',
 '500',
 '5000',
 '505060',
 '50award',
 '50ea',
 '50gbp',
 '50p',
 '50perweeksub',
 '50perwksub',
 '50pm',
 '50pmmorefrommobile2bremoved',
 '50ppm',
 '50rcvd',
 '50s',
 '515',
 '5226',
 '523',
 '5249',
 '526',
 '528',
 '530',
 '54',
 '542',
 '545',
 '5digital',
 '5free',
 '5ish',
 '5k',
 '5min',
 '5mls',
 '5p',
 '5pm',
 '5th',
 '5wb',
 '5we',
 '5wkg',
 '5wq',
 '5years',
 '60',
 '600',
 '6031',
 '6089',
 '60p',
 '61',
 '61200',
 '61610',
 '62220cncl',
 '6230',
 '62468',
 '62735',
 '630',
 '63miles',
 '645',
 '65',
 '650',
 '66',
 '6669',
 '674',
 '67441233',
 '68866',
 '69101',
 '69200',
 '69669',
 '69696',
 '69698',
 '69855',
 '69866',
 '69876',
 '69888',
 '69888nyt',
 '69911',
 '69969',
 '69988',
 '6days',
 '6hl',
 '6hrs',
 '6ish',
 '6missed',
 '6months',
 '6ph',
 '6pm',
 '6th',
 '6times',
 '6wu',
 '6zf',
 '700',
 '71',
 '7250',
 '7250i',
 '730',
 '731',
 '74355',
 '75',
 '750',
 '7548',
 '75max',
 '762',
 '7634',
 '7684',
 '77',
 '7732584351',
 '78',
 '786',
 '7876150ppm',
 '79',
 '7am',
 '7cfca1a',
 '7ish',
 '7mp',
 '7oz',
 '7pm',
 '7th',
 '7ws',
 '7zs',
 '80',
 '800',
 '8000930705',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300p',
 '80155',
 '80160',
 '80182',
 '8027',
 '80488',
 '80608',
 '8077',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '82050',
 '820554ad0a1705572711',
 '82242',
 '82277',
 '82324',
 '82468',
 '83021',
 '83039',
 '83049',
 '83110',
 '83118',
 '83222',
 '83332',
 '83338',
 '83355',
 '83370',
 '83383',
 '83435',
 '83600',
 '83738',
 '84',
 '84025',
 '84122',
 '84128',
 '84199',
 '84484',
 '85',
 '850',
 '85023',
 '85069',
 '85222',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '864233',
 '86688',
 '86888',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '8714714',
 '872',
 '87239',
 '87575',
 '8800',
 '88039',
 '88066',
 '88088',
 '88222',
 '88600',
 '88800',
 '8883',
 '88877',
 '88888',
 '89034',
 '89070',
 '89080',
 '89105',
 '89123',
 '89545',
 '89555',
 '89693',
 '89938',
 '8am',
 '8ball',
 '8lb',
 '8p',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '910',
 '9153',
 '9280114',
 '92h',
 '930',
 '9307622',
 '945',
 '946',
 '95',
 '9755',
 '9758',
 '97n7qp',
 '98321561',
 '99',
 '9996',
 '9ae',
 '9am',
 '9ja',
 '9pm',
 '9t',
 '9th',
 '9yt',
 '____',
 'a21',
 'a30',
 'aa',
 'aah',
 'aaniye',
 'aaooooright',
 'aathi',
 'ab',
 'abbey',
 'abdomen',
 'abeg',
 'abel',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'about',
 'aboutas',
 'above',
 'abroad',
 'absence',
 'absolutely',
 'absolutly',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'abuse',
 'abusers',
 'ac',
 'academic',
 'acc',
 'accent',
 'accenture',
 'accept',
 'access',
 'accessible',
 'accidant',
 'accident',
 'accidentally',
 'accommodation',
 'accommodationvouchers',
 'accomodate',
 'accomodations',
 'accordin',
 'accordingly',
 'account',
 'accounting',
 'accounts',
 'accumulation',
 'achan',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'aco',
 'across',
 'act',
 'acted',
 'actin',
 'acting',
 'action',
 'activ8',
 'activate',
 'active',
 'activities',
 'actor',
 'actual',
 'actually',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'adding',
 'address',
 'adds',
 'adewale',
 'adi',
 'adjustable',
 'admin',
 'administrator',
 'admirer',
 'admission',
 'admit',
 'adore',
 'adoring',
 'adp',
 'adress',
 'adrian',
 'adrink',
 'ads',
 'adsense',
 'adult',
 'adults',
 'advance',
 'adventure',
 'adventuring',
 'advice',
 'advise',
 'advising',
 'advisors',
 'aeronautics',
 'aeroplane',
 'afew',
 'affair',
 'affairs',
 'affection',
 'affectionate',
 'affections',
 'affidavit',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aft',
 'after',
 'afternon',
 'afternoon',
 'afternoons',
 'afterwards',
 'aftr',
 'ag',
 'again',
 'against',
 'agalla',
 'age',
 'age16',
 'age23',
 'agency',
 'agent',
 'agents',
 'ages',
 'agidhane',
 'aging',
 'ago',
 'agree',
 'ah',
 'aha',
 'ahead',
 'ahhh',
 'ahhhh',
 'ahmad',
 'ahold',
 'aid',
 ...]

In [34]:
vector.vocabulary_

{'go': 3563,
 'until': 8072,
 'jurong': 4365,
 'point': 5947,
 'crazy': 2332,
 'available': 1311,
 'only': 5561,
 'in': 4105,
 'bugis': 1761,
 'great': 3646,
 'world': 8536,
 'la': 4491,
 'buffet': 1759,
 'cine': 2055,
 'there': 7682,
 'got': 3607,
 'amore': 1077,
 'wat': 8312,
 'ok': 5528,
 'lar': 4527,
 'joking': 4333,
 'wif': 8438,
 'oni': 5557,
 'free': 3366,
 'entry': 2957,
 'wkly': 8494,
 'comp': 2172,
 'to': 7794,
 'win': 8451,
 'fa': 3094,
 'cup': 2392,
 'final': 3214,
 'tkts': 7781,
 '21st': 410,
 'may': 4949,
 '2005': 401,
 'text': 7633,
 '87121': 790,
 'receive': 6329,
 'question': 6221,
 'std': 7268,
 'txt': 7974,
 'rate': 6273,
 'apply': 1164,
 '08452810075over18': 77,
 'dun': 2809,
 'say': 6668,
 'so': 7063,
 'early': 2830,
 'hor': 3943,
 'already': 1049,
 'then': 7676,
 'nah': 5260,
 'don': 2718,
 'think': 7697,
 'he': 3796,
 'goes': 3571,
 'usf': 8118,
 'lives': 4682,
 'around': 1215,
 'here': 3847,
 'though': 7717,
 'freemsg': 3373,
 'hey': 3857,
 'darling': 2449,
 'it': 4236,
 'been': 1469,
 'week': 8359,
 'now': 5443,
 'and': 1092,
 'no': 5390,
 'word': 8527,
 'back': 1357,
 'like': 4632,
 'some': 7078,
 'fun': 3430,
 'you': 8656,
 'up': 8074,
 'for': 3316,
 'still': 7291,
 'tb': 7567,
 'xxx': 8602,
 'chgs': 2009,
 'send': 6760,
 '50': 612,
 'rcv': 6286,
 'even': 3006,
 'my': 5244,
 'brother': 1731,
 'is': 4224,
 'not': 5428,
 'speak': 7150,
 'with': 8480,
 'me': 4958,
 'they': 7690,
 'treat': 7904,
 'aids': 1000,
 'patent': 5747,
 'as': 1232,
 'per': 5790,
 'your': 8662,
 'request': 6438,
 'melle': 4988,
 'oru': 5618,
 'minnaminunginte': 5055,
 'nurungu': 5463,
 'vettam': 8176,
 'has': 3770,
 'set': 6787,
 'callertune': 1832,
 'all': 1036,
 'callers': 1831,
 'press': 6070,
 'copy': 2273,
 'friends': 3390,
 'winner': 8462,
 'valued': 8145,
 'network': 5339,
 'customer': 2405,
 'have': 3785,
 'selected': 6746,
 'receivea': 6330,
 '900': 822,
 'prize': 6102,
 'reward': 6493,
 'claim': 2061,
 'call': 1822,
 '09061701461': 222,
 'code': 2127,
 'kl341': 4454,
 'valid': 8141,
 '12': 321,
 'hours': 3963,
 'had': 3712,
 'mobile': 5109,
 '11': 310,
 'months': 5149,
 'or': 5594,
 'more': 5153,
 'entitled': 2954,
 'update': 8079,
 'the': 7662,
 'latest': 4541,
 'colour': 2148,
 'mobiles': 5110,
 'camera': 1843,
 'co': 2116,
 'on': 5549,
 '08002986030': 61,
 'gonna': 3587,
 'be': 1445,
 'home': 3916,
 'soon': 7105,
 'want': 8291,
 'talk': 7534,
 'about': 866,
 'this': 7706,
 'stuff': 7358,
 'anymore': 1131,
 'tonight': 7832,
 've': 8160,
 'cried': 2349,
 'enough': 2944,
 'today': 7801,
 'six': 6967,
 'chances': 1950,
 'cash': 1896,
 'from': 3407,
 '100': 296,
 '20': 396,
 '000': 1,
 'pounds': 6010,
 'csh11': 2368,
 '87575': 795,
 'cost': 2285,
 '150p': 350,
 'day': 2465,
 '6days': 686,
 '16': 362,
 'tsandcs': 7938,
 'reply': 6431,
 'hl': 3888,
 'info': 4140,
 'urgent': 8097,
 'won': 8511,
 'membership': 4994,
 'our': 5631,
 'jackpot': 4261,
 '81010': 743,
 'www': 8584,
 'dbuk': 2470,
 'net': 5333,
 'lccltd': 4559,
 'pobox': 5926,
 '4403ldnw1a7rw18': 563,
 'searching': 6715,
 'right': 6505,
 'words': 8528,
 'thank': 7650,
 'breather': 1700,
 'promise': 6135,
 'wont': 8518,
 'take': 7526,
 'help': 3833,
 'granted': 3635,
 'will': 8448,
 'fulfil': 3426,
 'wonderful': 8515,
 'blessing': 1576,
 'at': 1268,
 'times': 7759,
 'date': 2457,
 'sunday': 7426,
 'xxxmobilemovieclub': 8603,
 'use': 8112,
 'credit': 2339,
 'click': 2084,
 'wap': 8296,
 'link': 4654,
 'next': 5357,
 'message': 5012,
 'http': 3985,
 'com': 2151,
 'qjkgighjjgcbl': 6213,
 'oh': 5523,
 'watching': 8317,
 'eh': 2877,
 'remember': 6398,
 'how': 3969,
 'spell': 7165,
 'his': 3879,
 'name': 5266,
 'yes': 8639,
 'did': 2600,
 'naughty': 5293,
 'make': 4868,
 'wet': 8396,
 'fine': 3222,
 'if': 4058,
 'that': 7659,
 'way': 8329,
 'feel': 3165,
 'its': 4244,
 'gota': 3608,
 'england': 2935,
 'macedonia': 4830,
 'dont': 2722,
 'miss': 5071,
 'goals': 3567,
 'team': 7579,
 'news': 5353,
 'ur': 8093,
 'national': 5287,
 '87077': 789,
 'eg': 2872,
 'try': 7934,
 'wales': 8271,
 'scotland': 6694,
 '4txt': 604,
 'ú1': 8699,
 'poboxox36504w45wq': 5938,
 'seriously': 6780,
 'going': 3576,
 'ha': 3708,
 'pay': 5759,
 'first': 3239,
 'when': 8407,
 'da': 2422,
 'stock': 7294,
 'comin': 2162,
 'aft': 970,
 'finish': 3225,
 'lunch': 4796,
 'str': 7319,
 'down': 2744,
 'lor': 4737,
 'ard': 1190,
 'smth': 7046,
 'ffffffffff': 3184,
 'alright': 1050,
 'can': 1847,
 'meet': 4977,
 'sooner': 7106,
 'just': 4367,
 'forced': 3318,
 'myself': 5250,
 'eat': 2842,
 'slice': 6998,
 'really': 6311,
 'hungry': 4005,
 'tho': 7713,
 'sucks': 7395,
 'mark': 4905,
 'getting': 3523,
 'worried': 8539,
 'knows': 4465,
 'sick': 6916,
 'turn': 7957,
 'pizza': 5881,
 'lol': 4714,
 'always': 1059,
 'convincing': 2261,
 'catch': 1906,
 'bus': 1781,
 'are': 1191,
 'frying': 3415,
 'an': 1087,
 'egg': 2874,
 'tea': 7573,
 'eating': 2845,
 'mom': 5130,
 'left': 4583,
 'over': 5652,
 'dinner': 2631,
 'do': 2682,
 'love': 4759,
 'amp': 1079,
 'we': 8334,
 're': 6290,
 'packing': 5678,
 'car': 1868,
 'll': 4686,
 'let': 4604,
 'know': 4462,
 'room': 6546,
 'ahhh': 995,
 'work': 8529,
 'vaguely': 8137,
 'what': 8400,
 'does': 2694,
 'wait': 8265,
 'clear': 2078,
 'were': 8385,
 'sure': 7452,
 'being': 1487,
 'sarcastic': 6646,
 'why': 8431,
 'doesn': 2696,
 'live': 4678,
 'us': 8108,
 'yeah': 8627,
 'was': 8305,
 'apologetic': 1151,
 'fallen': 3119,
 'out': 5633,
 'she': 6832,
 'actin': 911,
 'spoilt': 7192,
 'child': 2017,
 'caught': 1910,
 'till': 7756,
 'but': 1788,
 'doing': 2708,
 'too': 7837,
 'badly': 1362,
 'cheers': 1993,
 'tell': 7597,
 'anything': 1137,
 'fear': 3157,
 'of': 5501,
 'fainting': 3111,
 'housework': 3967,
 'quick': 6224,
 'cuppa': 2394,
 'thanks': 7651,
 'subscription': 7383,
 'ringtone': 6514,
 'uk': 8004,
 'charged': 1962,
 'month': 5146,
 'please': 5906,
 'confirm': 2216,
 'by': 1805,
 'replying': 6432,
 'yup': 8683,
 'look': 4725,
 'timings': 7763,
 'msg': 5189,
 'again': 978,
 'xuhui': 8598,
 'learn': 4573,
 '2nd': 464,
 'her': 3846,
 'lesson': 4602,
 '8am': 815,
 'oops': 5572,
 'roommate': 6548,
 'done': 2720,
 'see': 6732,
 'letter': 4606,
 'decide': 2488,
 'hello': 3830,
 'saturday': 6659,
 'texting': 7641,
 'decided': 2489,
 'tomo': 7821,
 'trying': 7936,
 'invite': 4198,
 'pls': 5914,
 'ahead': 994,
 'watts': 8325,
 'wanted': 8293,
 'weekend': 8361,
 'abiola': 862,
 'forget': 3324,
 'need': 5313,
 'crave': 2329,
 'most': 5162,
 'sweet': 7483,
 'arabian': 1187,
 'steed': 7275,
 'mmmmmm': 5099,
 'yummy': 8678,
 '07732584351': 30,
 'rodger': 6536,
 'burns': 1778,
 'tried': 7913,
 'sms': 7041,
 'nokia': 5400,
 'camcorder': 1841,
 '08000930705': 57,
 'delivery': 2528,
 'tomorrow': 7823,
 'who': 8423,
 'seeing': 6734,
 'hope': 3934,
 'man': 4878,
 'well': 8376,
 'endowed': 2925,
 'am': 1061,
 'lt': 4783,
 'gt': 3675,
 'inches': 4109,
 'calls': 1837,
 'messages': 5014,
 'missed': 5073,
 'didn': 2602,
 'get': 3515,
 'hep': 3845,
 'immunisation': 4088,
 'nigeria': 5367,
 'fair': 3112,
 'hopefully': 3937,
 'tyler': 7987,
 'could': 2295,
 'maybe': 4951,
 'ask': 1242,
 'bit': 1553,
 'stubborn': 7347,
 'hospital': 3950,
 'kept': 4411,
 'telling': 7598,
 'weak': 8335,
 'sucker': 7393,
 'hospitals': 3951,
 'suckers': 7394,
 'thinked': 7698,
 'time': 7758,
 'saw': 6667,
 'class': 2070,
 'gram': 3627,
 'usually': 8124,
 'runs': 6589,
 'half': 3724,
 'eighth': 2880,
 'smarter': 7021,
 'gets': 3519,
 'almost': 1045,
 'whole': 8425,
 'second': 6719,
 'fyi': 3446,
 'ride': 6504,
 'morning': 5157,
 'crashing': 2328,
 'place': 5883,
 'wow': 8555,
 'never': 5344,
 'realized': 6309,
 'embarassed': 2905,
 'accomodations': 893,
 'thought': 7718,
 'liked': 4633,
 'since': 6941,
 'best': 1507,
 'seemed': 6738,
 'happy': 3759,
 'cave': 1914,
 'sorry': 7115,
 'give': 3544,
 'offered': 5509,
 'embarassing': 2906,
 'ac': 879,
 'sptv': 7214,
 'new': 5348,
 'jersey': 4303,
 'devils': 2580,
 'detroit': 2574,
 'red': 6352,
 'wings': 8460,
 'play': 5897,
 'ice': 4039,
 'hockey': 3901,
 'correct': 2278,
 'incorrect': 4120,
 'end': 2920,
 'mallika': 4877,
 'sherawat': 6839,
 'yesterday': 8641,
 'find': 3219,
 'url': 8104,
 'congrats': 2222,
 'year': 8628,
 'special': 7152,
 'cinema': 2056,
 'pass': 5736,
 'yours': 8666,
 '09061209465': 217,
 'suprman': 7450,
 'matrix3': 4938,
 'starwars3': 7256,
 'etc': 2994,
 'bx420': 1803,
 'ip4': 4207,
 '5we': 647,
 '150pm': 352,
 'later': 4540,
 'meeting': 4979,
 'where': 8411,
 'reached': 6293,
 'gauti': 3480,
 'sehwag': 6743,
 'odi': 5500,
 'series': 6778,
 'pick': 5853,
 'burger': 1773,
 'yourself': 8667,
 'move': 5175,
 'pain': 5685,
 'killing': 4436,
 'good': 3589,
 'joke': 4329,
 'girls': 3541,
 'situation': 6964,
 'seekers': 6735,
 'part': 5725,
 'checking': 1987,
 'iq': 4213,
 'roommates': 6549,
 'took': 7838,
 'forever': 3321,
 'come': 2157,
 'double': 2737,
 'check': 1983,
 'hair': 3719,
 'dresser': 2767,
 'said': 6615,
 'wun': 8583,
 'cut': 2409,
 'short': 6875,
 'nice': 5361,
 'pleased': 5907,
 'advise': 953,
 'following': 3298,
 'recent': 6333,
 'review': 6491,
 'mob': 5107,
 'awarded': 1328,
 '1500': 349,
 'bonus': 1617,
 '09066364589': 265,
 'song': 7100,
 'dedicated': 2499,
 'which': 8417,
 'dedicate': 2498,
 'valuable': 8143,
 'frnds': 3399,
 'rply': 6565,
 'complimentary': 2191,
 'trip': 7914,
 'eurodisinc': 3000,
 'trav': 7896,
 'aco': 907,
 'entry41': 2958,
 '1000': 297,
 'dis': 2643,
 '18': 367,
 'morefrmmob': 5154,
 'shracomorsglsuplt': 6900,
 '10': 295,
 'ls1': 4779,
 '3aj': 522,
 'hear': 3808,
 'divorce': 2672,
 'barbie': 1393,
 'comes': 2159,
 'ken': 4409,
 'plane': 5889,
 'wah': 8258,
 'lucky': 4790,
 'save': 6663,
 'money': 5137,
 'hee': 3821,
 'finished': 3227,
 'hi': 3861,
 'babe': 1348,
 'im': 4076,
 'wanna': 8289,
 'something': 7088,
 'xx': 8599,
 'performed': 5797,
 'waiting': 8268,
 'machan': 4832,
 'once': 5553,
 'thats': 7661,
 'cool': 2266,
 'gentleman': 3506,
 'dignity': 2621,
 'respect': 6458,
 'peoples': 5789,
 'very': 8175,
 'much': 5207,
 'shy': 6911,
 'pa': 5674,
 'operate': 5579,
 'after': 971,
 'same': 6631,
 'looking': 4729,
 'job': 4318,
 'ta': 7511,
 'earn': 2831,
 'ah': 992,
 'stop': 7304,
 'urgnt': 8100,
 'real': 6302,
 'yo': 8651,
 'tickets': 7746,
 'one': 5555,
 'jacket': 4260,
 'used': 8113,
 'multis': 5216,
 'started': 7251,
 'requests': 6439,
 'came': 1842,
 'bed': 1462,
 'coins': 2133,
 'factory': 3101,
 'gotta': 3612,
 'nitros': 5385,
 'ela': 2885,
 'kano': 4390,
 'il': 4070,
 'download': 2745,
 'wen': 8379,
 'stand': 7239,
 'close': 2091,
 'another': 1114,
 'night': 5369,
 'spent': 7170,
 'late': 4537,
 'afternoon': 973,
 'casualty': 1904,
 'means': 4965,
 'haven': 3787,
 'any': 1128,
 'stuff42moro': 7359,
 'includes': 4113,
 'sheets': 6834,
 'smile': 7029,
 'pleasure': 5909,
 'trouble': 7921,
 'pours': 6012,
 'rain': 6247,
 'sum1': 7417,
 'hurts': 4015,
 'becoz': 1460,
 'someone': 7082,
 'loves': 4767,
 'smiling': 7033,
 'service': 6783,
 'representative': 6436,
 '0800': 53,
 '169': 365,
 '6031': 653,
 'between': 1516,
 '10am': 305,
 '9pm': 842,
 'guaranteed': 3679,
 '5000': 614,
 'havent': 3788,
 'planning': 5893,
 'buy': 1793,
 'lido': 4617,
 '530': 633,
 'show': 6891,
 'collected': 2142,
 'simply': 6938,
 'password': 5743,
 'mix': 5089,
 '85069': 776,
 'verify': 8171,
 'usher': 8119,
 'britney': 1721,
 'fml': 3289,
 'po': 5924,
 'box': 1651,
 '5249': 630,
 'mk17': 5092,
 '92h': 827,
 '450ppw': 572,
 'telugu': 7603,
 'movie': 5178,
 'abt': 874,
 'loads': 4693,
 'loans': 4695,
 'wk': 8490,
 'hols': 3914,
 'run': 6587,
 'forgot': 3329,
 'hairdressers': 3721,
 'appointment': 1167,
 'four': 3347,
 'shower': 6893,
 'beforehand': 1476,
 'cause': 1911,
 'prob': 6107,
 'coffee': 2128,
 'animation': 1101,
 'nothing': 5433,
 'else': 2899,
 'okay': 5529,
 'price': 6083,
 'long': 4721,
 'legal': 4586,
 'them': 7672,
 'ave': 1315,
 'ams': 1083,
 'gone': 3585,
 '4the': 603,
 'driving': 2776,
 'test': 7627,
 'yet': 8642,
 'mean': 4961,
 'guess': 3685,
 'gave': 3481,
 'boston': 1638,
 'men': 4998,
 'changed': 1952,
 'search': 6714,
 'location': 4698,
 'nyc': 5474,
 'cuz': 2416,
 'signin': 6926,
 'page': 5681,
 'says': 6672,
 'umma': 8011,
 'life': 4620,
 'vava': 8157,
 'lot': 4745,
 'dear': 2478,
 'wishes': 8474,
 'birthday': 1551,
 'making': 4872,
 'truly': 7929,
 'memorable': 4995,
 'aight': 1002,
 'hit': 3881,
 'would': 8551,
 'ip': 4206,
 'address': 929,
 'considering': 2234,
 'computer': 2197,
 'isn': 4231,
 'minecraft': 5049,
 'server': 6782,
 'grumpy': 3672,
 'old': 5541,
 'people': 5788,
 'better': 1513,
 'lying': 4810,
 'jokes': 4331,
 'worry': 8541,
 'busy': 1787,
 'plural': 5918,
 'noun': 5440,
 'research': 6444,
 'cos': 2283,
 'things': 7696,
 'scared': 6678,
 'mah': 4855,
 'loud': 4754,
 'gent': 3504,
 'contact': 2239,
 'last': 4534,
 'weekends': 8362,
 'draw': 2759,
 'shows': 6899,
 '09064012160': 241,
 'k52': 4373,
 '12hrs': 332,
 '150ppm': 354,
 'wa': 8253,
 'openin': 5576,
 'sentence': 6771,
 'formal': 3333,
 'anyway': 1140,
 'juz': 4372,
 'tt': 7944,
 'eatin': 2844,
 'puttin': 6203,
 'weight': 8367,
 'haha': 3715,
 'anythin': 1136,
 'happened': 3751,
 'entered': 2947,
 'cabin': 1810,
 'boss': 1637,
 'felt': 3174,
 'askd': 1243,
 'invited': 4199,
 'apartment': 1145,
 'went': 8382,
 'specially': 7156,
 'holiday': 3911,
 'flights': 3265,
 'inc': 4107,
 'operator': 5580,
 '0871277810910p': 129,
 'min': 5042,
 'goodo': 3598,
 'must': 5235,
 'friday': 3385,
 'potato': 6004,
 'ratio': 6276,
 'tortilla': 7855,
 'needed': 5315,
 'hmm': 3893,
 'uncle': 8020,
 'informed': 4143,
 'paying': 5765,
 'school': 6684,
 'directly': 2637,
 'food': 3306,
 'private': 6099,
 '2004': 400,
 'account': 896,
 'statement': 7259,
 '07742676969': 32,
 '786': 715,
 'unredeemed': 8064,
 'points': 5948,
 '08719180248': 174,
 'identifier': 4051,
 '45239': 574,
 'expires': 3073,
 '2000': 398,
 'caller': 1830,
 '03': 15,
 'landline': 4514,
 '09064019788': 247,
 'box42wr29c': 1663,
 'apples': 1162,
 'pairs': 5689,
 'malarky': 4874,
 'todays': 7802,
 'voda': 8222,
 'numbers': 5460,
 'ending': 2922,
 '7548': 707,
 '350': 510,
 'award': 1327,
 'match': 4926,
 '08712300220': 111,
 'quoting': 6235,
 '4041': 547,
 'standard': 7240,
 'rates': 6274,
 'app': 1155,
 'sao': 6640,
 'mu': 5205,
 'predict': 6044,
 'buying': 1796,
 'yetunde': 8644,
 'hasn': 3772,
 'sent': 6770,
 'bother': 1641,
 'sending': 6762,
 'involve': 4203,
 'shouldn': 6886,
 'imposed': 4095,
 'apologise': 1152,
 'girl': 3538,
 'del': 2518,
 'bak': 1370,
 'sum': 7416,
 'lucyxx': 4793,
 'tmorrow': 7787,
 'accomodate': 892,
 'answer': 1117,
 'sunshine': 7433,
 'quiz': 6231,
 'top': 7846,
 'sony': 7102,
 'dvd': 2819,
 'player': 5899,
 'country': 2301,
 'algarve': 1029,
 'ansr': 1116,
 '82277': 750,
 'sp': 7137,
 'tyrone': 7991,
 'laid': 4506,
 'dogging': 2702,
 'locations': 4699,
 'direct': 2636,
 'join': 4326,
 'largest': 4531,
 'bt': 1747,
 'txting': 7980,
 'gravel': 3640,
 '69888': 681,
 'nt': 5450,
 'ec2a': 2847,
 '31p': 502,
 'haf': 3714,
 'msn': 5196,
 'yijue': 8648,
 'hotmail': 3958,
 'him': 3872,
 'rooms': 6550,
 'befor': 1474,
 'activities': 917,
 'msgs': 5195,
 'chat': 1973,
 'svc': 7468,
 'hardcore': 3761,
 'services': 6784,
 '69988': 685,
 'age': 981,
 'yr': 8673,
 'lazy': 4558,
 'type': 7988,
 'lect': 4580,
 'pouch': 6007,
 'sir': 6953,
 'mail': 4860,
 'swt': 7497,
 'nver': 5468,
 'tired': 7767,
 'little': 4677,
 'lovable': 4758,
 'persons': 5815,
 'coz': 2314,
 'somtimes': 7097,
 'those': 7714,
 'occupy': 5493,
 'biggest': 1533,
 'their': 7669,
 'hearts': 3814,
 'gud': 3681,
 'ni8': 5359,
 'open': 5573,
 'ya': 8612,
 'dot': 2736,
 'whats': 8402,
 'staff': 7231,
 'taking': 7531,
 'replied': 6429,
 'randy': 6267,
 'sexy': 6800,
 'female': 3175,
 'local': 4697,
 'luv': 4801,
 'netcollex': 5334,
 'ltd': 4784,
 '08700621170150p': 81,
 'ummma': 8013,
 'begin': 1480,
 'qatar': 6208,
 'pray': 6039,
 'hard': 3760,
 'deleted': 2522,
 'sindu': 6943,
 'birla': 1547,
 'soft': 7068,
 'wine': 8458,
 'flowing': 3280,
 'nevering': 5345,
 'thk': 7707,
 'plaza': 5904,
 'typical': 7990,
 'everywhere': 3024,
 'dirt': 2640,
 'floor': 3274,
 'windows': 8455,
 'shirt': 6854,
 'sometimes': 7090,
 'mouth': 5174,
 'dream': 2762,
 'without': 8484,
 'chores': 2044,
 ...}

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_vector,df_mails['SpamMail'],test_size=0.2)

In [28]:
email=df_mails[:2]

In [29]:
email

                                             Message  SpamMail
0  Go until jurong point, crazy.. Available only ...         0
1                      Ok lar... Joking wif u oni...         0

In [30]:
from sklearn.naive_bayes import MultinomialNB

model_spam=MultinomialNB()

In [31]:
model_spam.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [33]:
model_spam.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
model_spam.score(X_test,y_test)

0.9856502242152466

In [75]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [76]:
vector.transform(emails)

<2x8700 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [77]:
model_spam.predict(vector.transform(emails))

array([0, 1], dtype=int64)

In [42]:
df_m_data=pd.read_csv('E:\Personal\DataScience\MachineLearning\SpamMails.csv',encoding = 'unicode_escape')

In [45]:
df_m_data.groupby('Category').count()

                                                    Message  Unnamed: 2
Category
ham                                                    4825           0
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...        1           1
ham     Yeah                                              1           0
spam                                                    747           0

In [47]:
df_m_data.drop('Unnamed: 2',axis=1, inplace=True)

In [48]:
df_m_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [54]:
df_m_data.groupby('Category').describe()

                                                   Message         \
                                                     count unique
Category
ham                                                   4825   4516
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...       1      1
ham     Yeah                                             1      1
spam                                                   747    640

                                                                                                       \
                                                                                                  top
Category
ham                                                                            Sorry, I'll call later
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...                                DEVIOUSBITCH.ANYWAY
ham     Yeah                                                    give me a call if you've got a minute
spam                                                Please call our customer service representativ...


                                                   freq
Category
ham                                                  30
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...    1
ham     Yeah                                          1
spam                                                  4

We will be using pipeline method here so that CountVectorizer and multinomialNB are fitted in one step

In [78]:
from sklearn.pipeline import Pipeline

In [85]:
pip_model=Pipeline([('vectorize',CountVectorizer()),('nb',MultinomialNB())])

In [86]:
X_train,X_test,y_train,y_test=train_test_split(df_mails['Message'],df_mails['SpamMail'],test_size=0.2)

In [87]:
pip_model.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('vectorize', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [88]:
pip_model.predict(emails)

array([0, 1], dtype=int64)

In [89]:
pip_model.score(X_test,y_test)

0.9847533632286996